"""tests/test_openapi_contract.py — the typed contract and its committed spec (atrium-project#32).

WHY THIS EXISTS. The AMČR pipeline's Temporal activities are generated from the ``openapi.json``
attached to the tool release AMČR trusts, and a running service's ``/openapi.json`` is read only
to check that the deployed image matches that release (motyc, atrium-project#32, 2026-09-27).
That holds only if, in every repository:

* the spec is COMMITTED (``service/openapi.json``) and is exactly what the code generates —
  ``info.version`` aside, which ``atrium_openapi.py stamp`` sets at release time;
* the spec depends on nothing but the code: not on the environment (every ``[limit]`` variable
  and the repo's ``ENV_PERTURB`` settings are changed and the spec must not move), and not on
  whichever fastapi or pydantic pip resolved (both pinned exactly, and the installed versions
  must be the pins);
* every primary endpoint's 200 is a named model, every error response is the ``ErrorBody``
  (§4.4), FastAPI's own ``HTTPValidationError`` — not the body the services send — is gone, and
  the operationIds are the route names a generated client's methods are named after;
* the reason-code registry and the record schema are published with it, and ``/info``
  ``openapi_sha256`` is the digest of the committed spec, so a deployed image can be checked;
* real responses conform to the PUBLISHED schema, not only to the models it came from.

Canonical copy: the hub's ``docs/templates/shared/``, vendored to ``tests/`` in every tool repo
(MANIFEST, para-drift). What differs per repo — the services, their app imports and specs, the
settings to perturb, the pin files, the torch stub page-classification needs — is declared in the
repo-local ``tests/openapi_contract_data.py`` (a MANIFEST precondition, never vendored). The file
skips in the hub, which has no service. Regenerate a spec after an API change with::

    python atrium_openapi.py export --app service.api:app --out service/openapi.json
"""

from __future__ import annotations

import importlib
import importlib.metadata
import json
import os
import re
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent

if not (REPO_ROOT / "tests" / "openapi_contract_data.py").is_file():
    pytest.skip(
        "no tests/openapi_contract_data.py here — this file checks a TOOL REPO's services, and the "
        "hub's docs/templates/shared/ is not one (atrium-project#32)",
        allow_module_level=True,
    )

pytest.importorskip("fastapi")

if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from fastapi.routing import APIRoute  # noqa: E402
from fastapi.testclient import TestClient  # noqa: E402

import atrium_openapi  # noqa: E402

DATA = importlib.import_module("tests.openapi_contract_data")
SERVICES = list(DATA.SERVICES)
PREPARE = getattr(DATA, "PREPARE", None)

#: The packages the committed spec is a function of, pinned exactly in every file of ``PIN_FILES``.
PINNED = ("fastapi", "pydantic")


def _app(entry):
    """The service's app; only a missing dependency skips (a broken import must fail)."""
    try:
        if PREPARE:
            atrium_openapi._call(PREPARE)()
        return atrium_openapi._call(entry["app"])
    except ImportError as exc:
        pytest.skip(f"cannot import {entry['app']}: {exc}")


def _live(entry):
    return json.loads(json.dumps(_app(entry).openapi()))


def _committed(entry):
    path = REPO_ROOT / entry["spec"]
    assert path.is_file(), f"{entry['spec']} is not committed; write it with atrium_openapi.py export"
    return atrium_openapi.load(path)


def _operations(spec):
    for path, item in spec.get("paths", {}).items():
        for method, operation in item.items():
            yield path, method, operation


IDS = [entry["service"] + ":" + entry["app"] for entry in SERVICES]


# ── the pins ───────────────────────────────────────────────────────────────────────────────


def _pins(path: Path):
    pins = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        match = re.match(r"^([A-Za-z0-9_.-]+)(\[[^\]]*\])?\s*==\s*([^\s;]+)", line)
        if match and match.group(1).lower() in PINNED:
            pins[match.group(1).lower()] = match.group(3)
    return pins


def test_fastapi_and_pydantic_are_pinned_exactly_everywhere_and_installed_as_pinned():
    """The spec is generated by fastapi and pydantic: one version of each, in every lane and image."""
    seen = {}
    for name in DATA.PIN_FILES:
        pins = _pins(REPO_ROOT / name)
        missing = [pkg for pkg in PINNED if pkg not in pins]
        assert not missing, f"{name} does not pin {missing} with == (atrium-project#32: the spec depends on them)"
        seen[name] = pins
    versions = {pkg: {pins[pkg] for pins in seen.values()} for pkg in PINNED}
    assert all(len(v) == 1 for v in versions.values()), f"the pin files disagree: {seen}"
    for pkg in PINNED:
        pinned = versions[pkg].pop()
        installed = importlib.metadata.version(pkg)
        assert installed == pinned, (
            f"{pkg} {installed} is installed but {pinned} is pinned: install the pins "
            f"(pip install -r {DATA.PIN_FILES[0]}) before comparing specs"
        )


# ── the committed spec ─────────────────────────────────────────────────────────────────────


@pytest.mark.parametrize("entry", SERVICES, ids=IDS)
def test_committed_spec_is_what_the_code_generates(entry):
    problems = atrium_openapi.check(_committed(entry), _live(entry))
    assert not problems, (
        f"{entry['spec']} is stale:\n  " + "\n  ".join(problems) + "\nRegenerate it: python atrium_openapi.py "
        f"export --app {entry['app']} --out {entry['spec']}" + (f" --prepare {PREPARE}" if PREPARE else "")
    )


@pytest.mark.parametrize("entry", SERVICES, ids=IDS)
def test_committed_spec_is_valid_openapi(entry):
    validator = pytest.importorskip("openapi_spec_validator")
    validator.validate(_committed(entry))


def _perturbed_env():
    env = dict(os.environ)
    try:
        limits = importlib.import_module("tool_limits").LIMITS
    except ImportError:
        limits = []
    for spec in limits:
        step = 1 if spec.kind is int else 0.5
        other = spec.default + step
        if spec.maximum is not None and other > spec.maximum:
            other = spec.default - step
        if (spec.minimum is not None and other < spec.minimum) or other < 0:
            continue
        env[spec.env] = str(other)
    env.update({key: str(value) for key, value in getattr(DATA, "ENV_PERTURB", {}).items()})
    return env


@pytest.mark.parametrize("entry", SERVICES, ids=IDS)
def test_spec_does_not_depend_on_the_environment(entry):
    """A deployment that changes any setting must still serve the spec its release carries."""
    _app(entry)  # skip here, not in the subprocess, when a dependency is missing
    command = [sys.executable, "atrium_openapi.py", "export", "--app", entry["app"], "--out", "-"]
    if PREPARE:
        command += ["--prepare", PREPARE]
    proc = subprocess.run(command, cwd=REPO_ROOT, env=_perturbed_env(), capture_output=True, text=True, check=False)
    assert proc.returncode == 0, proc.stderr[-4000:]
    problems = atrium_openapi.check(_committed(entry), json.loads(proc.stdout))
    assert not problems, "the spec changes with the environment:\n  " + "\n  ".join(problems)


# ── what the spec says ─────────────────────────────────────────────────────────────────────


@pytest.mark.parametrize("entry", SERVICES, ids=IDS)
def test_every_primary_endpoint_returns_a_named_model(entry):
    spec = _committed(entry)
    for path in entry["primary"]:
        assert path in spec["paths"], f"primary endpoint {path} is not in the spec"
        for method, operation in spec["paths"][path].items():
            schema = operation["responses"]["200"].get("content", {}).get("application/json", {}).get("schema")
            assert schema is not None and set(schema) == {"$ref"}, (
                f"{method.upper()} {path}: the JSON 200 must be exactly a $ref to a model, not {schema!r} — "
                "declare response_model=None, responses={200: {'model': ...}}"
            )


@pytest.mark.parametrize("entry", SERVICES, ids=IDS)
def test_every_error_response_is_the_error_body(entry):
    spec = _committed(entry)
    wrong = []
    for path, method, operation in _operations(spec):
        for status, response in operation.get("responses", {}).items():
            if not status.isdigit() or int(status) < 400:
                continue
            if path in ("/health", "/ready") and status == "503":
                continue  # HealthBody / ReadyBody: their own bodies, by design (§4.1)
            schema = response.get("content", {}).get("application/json", {}).get("schema")
            if schema != {"$ref": "#/components/schemas/ErrorBody"}:
                wrong.append(f"{method.upper()} {path} {status}: {schema!r}")
    assert not wrong, "error responses not declared as ErrorBody:\n  " + "\n  ".join(wrong)


@pytest.mark.parametrize("entry", SERVICES, ids=IDS)
def test_no_fastapi_default_error_schema_and_no_split_models(entry):
    names = set(_committed(entry).get("components", {}).get("schemas", {}))
    assert not names & {"HTTPValidationError", "ValidationError"}, "FastAPI's own 422 body is documented"
    split = sorted(n for n in names if n.endswith("-Input") or n.endswith("-Output"))
    assert not split, f"pydantic split these models into input/output variants: {split}"


@pytest.mark.parametrize("entry", SERVICES, ids=IDS)
def test_the_reason_registry_is_published(entry):
    from service.atrium_service import REASON_CODES, REASON_STATUSES

    spec = _committed(entry)
    published = spec.get("x-atrium-reason-codes") or {}
    assert set(published) == set(REASON_CODES)
    for code, entry_ in published.items():
        assert entry_["statuses"] == list(REASON_STATUSES[code]), code
    assert spec["info"].get("x-atrium-service") == entry["service"]


@pytest.mark.parametrize("entry", SERVICES, ids=IDS)
def test_operation_ids_are_the_route_names(entry):
    app = _app(entry)
    spec = _committed(entry)
    for route in app.routes:
        if not isinstance(route, APIRoute) or not route.include_in_schema:
            continue
        for method in route.methods:
            operation = spec["paths"][route.path_format][method.lower()]
            assert operation["operationId"] == route.name, f"{method} {route.path}: {operation['operationId']!r}"


@pytest.mark.parametrize("entry", SERVICES, ids=IDS)
def test_the_record_schema_is_the_vendored_one(entry):
    spec = _committed(entry)
    schemas = spec.get("components", {}).get("schemas", {})
    if "AtriumDocument" not in schemas:
        pytest.skip("this service returns no record")
    import atrium_document

    record = atrium_document.load_schema()
    assert spec["x-atrium-record-schema"] == {
        "schema_version": atrium_document.SCHEMA_VERSION,
        "sha256": atrium_openapi.digest(record),
    }
    assert schemas["AtriumDocument"].get("title") == record.get("title")
    assert "$defs" not in schemas["AtriumDocument"] and "$id" not in schemas["AtriumDocument"]
    for name in record.get("$defs", {}):
        assert f"AtriumDocument_{name}" in schemas, f"$defs/{name} was not hoisted"


# ── real responses against the published schema ───────────────────────────────────────────


@pytest.mark.parametrize("entry", SERVICES, ids=IDS)
def test_info_reports_the_digest_of_the_committed_spec(entry):
    app = _app(entry)
    body = TestClient(app).get("/info").json()
    expected = atrium_openapi.digest(atrium_openapi.stamp(_committed(entry), app.version))
    assert body["openapi_sha256"] == expected, "/info openapi_sha256 is not the committed spec's digest"


@pytest.mark.parametrize("entry", SERVICES, ids=IDS)
def test_meta_responses_conform_to_the_published_schema(entry):
    pytest.importorskip("jsonschema")
    spec = _committed(entry)
    client = TestClient(_app(entry))
    info = client.get("/info")
    atrium_openapi.validate_response(spec, "/info", "get", info.status_code, info.json())
    health = client.get("/health")
    atrium_openapi.validate_response(spec, "/health", "get", health.status_code, health.json())
    if "/ready" in spec["paths"]:
        ready = client.get("/ready")
        atrium_openapi.validate_response(spec, "/ready", "get", ready.status_code, ready.json())
    missing = client.get("/no-such-route")
    schema = {"$ref": "#/components/schemas/ErrorBody", "components": spec["components"]}
    import jsonschema

    jsonschema.Draft202012Validator(schema).validate(missing.json())
