name: Docker Build & Publish

on:
  push:
    branches: [test, master]
    tags: ['v*']
  pull_request:
    branches: [test, master]
  release:
    types: [published]

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ufal/atrium-project/.github/workflows/docker-tool.reusable.yml@test
    secrets: inherit
    with:
      image-name: ufal/atrium-page-classification
      apt-packages: build-essential g++ libgl1 libglib2.0-0 poppler-utils
      pre-install-torch: torch==2.7.1 torchvision==0.22.1
      requirements: setup/requirements.txt setup/requirements-test.txt
      hf-model-cache: true